# Pytorch Fundamentals

In [105]:
import torch
import numpy as np
torch.__version__

'1.13.1'

## Scalar

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
# dimension
scalar.ndim

0

In [14]:
# Retrieve the number from tensor
scalar.item()

7

## Vector

In [15]:
vector = torch.tensor([3,2])
vector

tensor([3, 2])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [20]:
# size method is used when we need to know the size of the tensor along a specific dimension
vector.size()

torch.Size([2])

## Matrix

In [22]:
matrix = torch.tensor([[1,2],
                       [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [28]:
matrix.ndim

2

In [23]:
vector.shape

torch.Size([2])

In [25]:
vector.size(0)

2

## Tensor

In [29]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [32]:
print(TENSOR.size(0))
print(TENSOR.size(1))
print(TENSOR.size(2))

1
3
3


## Tensor of Random numbers

In [40]:
random_tensor = torch.rand((4,3,2))
random_tensor

tensor([[[0.0222, 0.1848],
         [0.6825, 0.1750],
         [0.0218, 0.2659]],

        [[0.4544, 0.7360],
         [0.0991, 0.6418],
         [0.8451, 0.5970]],

        [[0.6039, 0.5498],
         [0.4393, 0.3721],
         [0.9125, 0.4706]],

        [[0.7759, 0.4943],
         [0.8077, 0.9058],
         [0.9664, 0.5441]]])

In [42]:
# data type
random_tensor.dtype

torch.float32

In [43]:
# zeros and ones
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range and tensors like¶

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.
You can use torch.arange(start, end, step) to do so.

In [46]:
zero_to_ten = torch.arange(1,10,1)
zero_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
zero_to_ten.dtype

torch.int64

In [48]:
zero_to_ten.device

device(type='cpu')

## Matrix multiplication (is all you need)

In [49]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [50]:
tensor * tensor

tensor([1, 4, 9])

In [51]:
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
tensor @ tensor

tensor(14)

In [53]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.39 ms, sys: 4.78 ms, total: 6.17 ms
Wall time: 16.2 ms


tensor(14)

In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 497 µs, sys: 282 µs, total: 779 µs
Wall time: 599 µs


tensor(14)

In [55]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [57]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Reshaping, stacking, squeezing and unsqueezing¶

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

In [62]:
tensor = torch.arange(1,9,1)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
reshaped = tensor.reshape(2,4)
reshaped

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [65]:
tensor.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [69]:
torch.stack([tensor,tensor], dim = 0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5, 6, 7, 8]])

In [70]:
torch.stack([tensor,tensor], dim = 1)

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8]])

In [76]:
# squeeze only works with 1 dimension to no dimension
squeeze = tensor.squeeze()
print(squeeze, squeeze.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([8])


## Indexing (selecting data from tensors)¶

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

In [77]:
tensor = torch.arange(1,10)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
tensor = tensor.reshape(1, 3, 3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [83]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
tensor[0][0]

tensor([1, 2, 3])

In [85]:
tensor[0][0][0]

tensor(1)

In [79]:
tensor[: , 0]

tensor([[1, 2, 3]])

In [82]:
tensor[: ,:, 2]

tensor([[3, 6, 9]])

In [88]:
tensor[:, 1, 1]

tensor([5])

## PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.


In [90]:
array = np.arange(1, 10)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [91]:
tensor.numpy()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reproducibility (trying to take the random out of random)¶

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

In [92]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)

## Running tensors on GPUs (and making faster computations)

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.



In [94]:
! pip3 install torch torchvision torchaudio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 MB 1.5 MB/s eta 0:00:0000:0100:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 1.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.1 MB/s eta 0:00:0000:0100:010m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 1.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 1.8 MB/s eta 0:00:00a 0:00:01
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.9/168.9 kB 1.7 MB/s eta 0:00:00a 0:00:01
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 1.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.0/119.0 kB 2.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.6/104.6 kB 1.8 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 1.9 MB/s eta 0:00:00a 0:00:0

In [96]:
# Check for GPU
torch.cuda.is_available()

False

In [97]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [98]:
torch.cuda.is_available()

False

In [100]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)

In [101]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
! git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .ipynb_checkpoints/00_pytorch_fundamentals-checkpoint.ipynb
	modified:   00_pytorch_fundamentals.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	00_pytorch_fundamentals_exercises.ipynb

no changes added to commit (use "git add" and/or "git commit -a")
