# Pytorch Fundamentals

In [2]:
import torch
torch.__version__

'1.13.1'

## Scalar

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
# dimension
scalar.ndim

0

In [14]:
# Retrieve the number from tensor
scalar.item()

7

## Vector

In [15]:
vector = torch.tensor([3,2])
vector

tensor([3, 2])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [20]:
# size method is used when we need to know the size of the tensor along a specific dimension
vector.size()

torch.Size([2])

## Matrix

In [22]:
matrix = torch.tensor([[1,2],
                       [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [28]:
matrix.ndim

2

In [23]:
vector.shape

torch.Size([2])

In [25]:
vector.size(0)

2

## Tensor

In [29]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [32]:
print(TENSOR.size(0))
print(TENSOR.size(1))
print(TENSOR.size(2))

1
3
3


## Tensor of Random numbers

In [40]:
random_tensor = torch.rand((4,3,2))
random_tensor

tensor([[[0.0222, 0.1848],
         [0.6825, 0.1750],
         [0.0218, 0.2659]],

        [[0.4544, 0.7360],
         [0.0991, 0.6418],
         [0.8451, 0.5970]],

        [[0.6039, 0.5498],
         [0.4393, 0.3721],
         [0.9125, 0.4706]],

        [[0.7759, 0.4943],
         [0.8077, 0.9058],
         [0.9664, 0.5441]]])

In [42]:
# data type
random_tensor.dtype

torch.float32

In [43]:
# zeros and ones
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Creating a range and tensors like¶

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.
You can use torch.arange(start, end, step) to do so.

In [46]:
zero_to_ten = torch.arange(1,10,1)
zero_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
zero_to_ten.dtype

torch.int64

In [48]:
zero_to_ten.device

device(type='cpu')

## Matrix multiplication (is all you need)

In [49]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [50]:
tensor * tensor

tensor([1, 4, 9])

In [51]:
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
tensor @ tensor

tensor(14)

In [53]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.39 ms, sys: 4.78 ms, total: 6.17 ms
Wall time: 16.2 ms


tensor(14)

In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 497 µs, sys: 282 µs, total: 779 µs
Wall time: 599 µs


tensor(14)

In [55]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [57]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])